### ISSUE TITLE
Can you provide the point_cloud.ply of in2d-data

### ISSUE THREAD

**Issue by MacLLL** [buaacyw/GaussianEditor#12]
Same as title

**Comment by buaacyw** [comment]
Sorry for the late response.
You can find it [here](https://huggingface.co/datasets/Yiwen-ntu/GaussianEditor_Result/tree/main/InstructNeRF2NeRF_PLY_Files).

**Comment by ThePassedWind** [comment]
Plus, Could we get the new point cloud after deleting an object or adding a new object?
And, How can we render new images from novel views?
