### ISSUE TITLE
can't download the plugins in Win10

### ISSUE THREAD

**Issue by Larissa0829** [buaacyw/GaussianEditor#13]
when i run <pip install -r requirements.txt>,always some plugins can not be downloaded.
![$WWEJO0EIBGYPCHV)`YI19I](https://github.com/buaacyw/GaussianEditor/assets/142070036/60110aa9-18a7-4053-ae73-4ebb37deb5e9)

**Comment by buaacyw** [comment]
It seems like you failed to install https://github.com/ashawkey/kiuikit because of failed SSL request.
Can you try solely install https://github.com/ashawkey/kiuikit?
