### ISSUE TITLE
Windows10 Installation Guide

### ISSUE THREAD

**Issue by zhanghongyong123456** [buaacyw/GaussianEditor#14]
windows10  CUDA 11.7   RTX 8000  VS2019
<1>. Installation of basic environment (基础环境安装)
1.1   Create a virtual environment and install torch 创建虚拟环境、安装  torch）
conda create -n  GaussianEditor python=3.10  
conda activate GaussianEditor 
conda install pytorch==2.0.1 torchvision==0.15.2 torchaudio==2.0.2 pytorch-cuda=11.7 -c pytorch -c nvidia

1.2  pip install xformers==0.0.20 

1.3 remove  git+https://github.com/NVlabs/tiny-cuda-nn/#subdirectory=bindings/torch   in requirements_2.txt  and    pip install -r  requirements_2.txt
![image](https://github.com/buaacyw/GaussianEditor/assets/48466610/35bb5f82-34e6-4551-a796-bc2d59af7864)

1.4  Source code compilation 源码编译 tiny-cuda-nn
git clone --recursive https://github.com/nvlabs/tiny-cuda-nn  
open x64 Native Tools Command Prompt for VS 2019
conda activate  GaussianEditor
cd  tiny-cuda-nn\bindings\torch
then run 
python setup.py install

1.5 Source code compilation 源码编译  GroundingDINO:
git clone https://github.com/IDEA-Research/GroundingDINO.git
conda activate  GaussianEditor
cd GroundingDINO
pip install -e .

1.6 Source code compilation 源码编译  lang-segment-anything
git clone https://github.com/luca-medeiros/lang-segment-anything && cd lang-segment-anything
去掉   pyproject.toml  中对于  groundingdino 依赖
![image](https://github.com/buaacyw/GaussianEditor/assets/48466610/a11b438f-5965-4d5c-8aed-4bd857767997)

#groundingdino = {git = "https://github.com/IDEA-Research/GroundingDINO.git"}  line 26   remove 
pip install -e .
1.7   install simple-knn diff-gaussian-rasterization
cd gaussiansplatting/submodules
pip install ./diff-gaussian-rasterization
pip install ./simple-knn
pip install kornia==0.7.0

<2>. Installation of Viser environment (Viser环境安装)

mkdir extern && cd extern
git clone https://github.com/heheyas/viser 
pip install -e viser
Modified Viser source code for windows builds（接下来修改Viser 源代码用于windows构建）
path\to\you\extern\viser\src\viser\_viser.py   line 326
![image](https://github.com/buaacyw/GaussianEditor/assets/48466610/9a219881-9d51-4e0f-be24-fb7622621f12)
2.1  install node env:  path\to\you\extern\viser\src\viser\_client_autobuild.py
![image](https://github.com/buaacyw/GaussianEditor/assets/48466610/b8eecb89-0cf8-467e-b738-b7744619cd34)
![image](https://github.com/buaacyw/GaussianEditor/assets/48466610/26b4e243-9063-4d90-b725-e619398f5489)
when i  run  ,i find  this error(运行时发现这个错误)：
![02](https://github.com/buaacyw/GaussianEditor/assets/48466610/41a89a65-044f-422a-9fb0-d9eafba66cff)
Install cmd manually under administrator rights （管理员权限手动安装）

cd  path\to\your\GaussianEditor\extern\viser\src\viser\client
conda activate GaussianEditor
python -m nodeenv --node=20.4.0  .nodeenv

![image](https://github.com/buaacyw/GaussianEditor/assets/48466610/a3e3306c-129b-4586-948f-129d1fe0eee9)
![image](https://github.com/buaacyw/GaussianEditor/assets/48466610/2fcd229b-67e4-47ff-90a4-30ad4f9d74b6)
![image](https://github.com/buaacyw/GaussianEditor/assets/48466610/0362d318-069b-4a7f-8ca8-d676bf81b65d)

2.2 build  yarn  file (构建yarn文件夹)

![image](https://github.com/buaacyw/GaussianEditor/assets/48466610/208a2aae-b9a0-40b0-90a6-04952374f259)
![image](https://github.com/buaacyw/GaussianEditor/assets/48466610/f6959997-b2fd-4e6c-b6f4-b0ce4c4eff1e)

2.3  Source code modification(需要修改源码的地方)
path\to\you\GaussianEditor\extern\viser\src\viser\_client_autobuild.py     replace  this script

    
[_client_autobuild.txt](https://github.com/buaacyw/GaussianEditor/files/13672309/_client_autobuild.txt)

3. run  webui.py,  It's OK

**Comment by buaacyw** [comment]
Thanks a lot for your guide!

**Comment by GluttonK** [comment]
感谢实践经验的分享

**Comment by TonyDua** [comment]
Additional information:
If you encounter the error "from kornia.geometry.quaternion import Quaternion.ModuleNotFoundError: No module named 'kornia.geometry.quaternion" while running webui.py, please check your kornia version. If it is 0.5, uninstall it and install the latest version.
`pip uninstall Kornia`
Then
`pip install Kornia`
