### ISSUE TITLE
Could you tell me where to download "omnidata_dpt_depth_v2.ckpt"?

### ISSUE THREAD

**Issue by MnKnight1** [buaacyw/GaussianEditor#15]
I see that I have to download `omnidata_dpt_depth_v2.ckpt` in `GaussianEditor-master/threestudio/utils/dpt.py`
Because of the server network, I had to load it locally and could not download it online，could you tell me where to download "omnidata_dpt_depth_v2.ckpt"?Is it same as https://github.com/ashawkey/stable-dreamfusion/blob/5550b91862a3af7842bb04875b7f1211e5095a63/readme.md?plain=1#L68  ？

```
         if self.mode == "depth":
            path = ".cache/dpt/omnidata_dpt_depth_v2.ckpt"
            self.model = DPTDepthModel(backbone="vitb_rn50_384")
            self.aug = transforms.Compose(
                [
                    transforms.Resize((384, 384)),
                    transforms.Normalize(mean=0.5, std=0.5),
                ]
            )
        elif self.mode == "normal":
            path = ".cache/dpt/omnidata_dpt_normal_v2.ckpt"
            self.model = DPTDepthModel(backbone="vitb_rn50_384", num_channels=3)
            self.aug = transforms.Compose(
                [
                    transforms.Resize((384, 384)),
                ]
            )
```

**Comment by zhanghongyong123456** [comment]
> I see that I have to download `omnidata_dpt_depth_v2.ckpt` in `GaussianEditor-master/threestudio/utils/dpt.py` Because of the server network, I had to load it locally and could not download it online，could you tell me where to download "omnidata_dpt_depth_v2.ckpt"?Is it same as https://github.com/ashawkey/stable-dreamfusion/blob/5550b91862a3af7842bb04875b7f1211e5095a63/readme.md?plain=1#L68 ？
> 
> ```
>          if self.mode == "depth":
>             path = ".cache/dpt/omnidata_dpt_depth_v2.ckpt"
>             self.model = DPTDepthModel(backbone="vitb_rn50_384")
>             self.aug = transforms.Compose(
>                 [
>                     transforms.Resize((384, 384)),
>                     transforms.Normalize(mean=0.5, std=0.5),
>                 ]
>             )
>         elif self.mode == "normal":
>             path = ".cache/dpt/omnidata_dpt_normal_v2.ckpt"
>             self.model = DPTDepthModel(backbone="vitb_rn50_384", num_channels=3)
>             self.aug = transforms.Compose(
>                 [
>                     transforms.Resize((384, 384)),
>                 ]
>             )
> ```

you can  download  https://huggingface.co/camenduru/PeRF/tree/main

**Comment by heheyas** [comment]
Check #10 for manually downloading the weight for the depth estimator. 

[Reference](https://github.com/EPFL-VILAB/omnidata/tree/main/omnidata_tools/torch)

**Comment by MnKnight1** [comment]
Thank you for your help！
