### ISSUE TITLE
about   test   (1) Semantic Tracing by Text  , i  have this results,<>

### ISSUE THREAD

**Issue by zhanghongyong123456** [buaacyw/GaussianEditor#16]
my cmd args:  --colmap_dir
./dataset/bicycle
--gs_source
./dataset/bicycle/point_cloud/iteration_7000/point_cloud.ply
![image](https://github.com/buaacyw/GaussianEditor/assets/48466610/6cd99791-3611-41f9-b5d8-16c7428a819b)
![image](https://github.com/buaacyw/GaussianEditor/assets/48466610/682130e3-a068-4793-a3da-ffdd18ae550d)

**Comment by buaacyw** [comment]
"None a bike detected" means that for that single view, the target is not detected.
This is normal since the bike doesn't appear for some camera views.
