### ISSUE TITLE
Where can I get the sparse folder of "face"

### ISSUE THREAD

**Issue by Yuxuan-W** [buaacyw/GaussianEditor#19]
Thanks for your inspiring work. I found you provide the .ply file for the scene "face" in instruct-N2N data. Do you know how to generate its corresponding "sparse" folder of COLMAP required by the code?

**Comment by buaacyw** [comment]
Thanks! Have uploaded [here](https://huggingface.co/datasets/Yiwen-ntu/GaussianEditor_Result/tree/main/InstructNeRF2NeRF_PLY_Files)
