### ISSUE TITLE
 pip install -e viser

### ISSUE THREAD

**Issue by Tiandishihua** [buaacyw/GaussianEditor#2]
ERROR: Project file:///app/extern/viser has a 'pyproject.toml' and its build backend is missing the 'build_editable' hook. Since it does not have a 'setup.py' nor a 'setup.cfg', it cannot be installed in editable mode. Consider using a build backend that supports PEP 660.

**Comment by buaacyw** [comment]
Thanks for your interest. But I haven't encountered this error.
Could you please provide more information about your environment?

**Comment by buaacyw** [comment]
Could you please have a try to install the origin Viser by
pip install viser

**Comment by Tiandishihua** [comment]
Solution：
1.pip install viser
2. git clone https://github.com/heheyas/viser 
3. pip install -e viser
4. cd ..

**Comment by buaacyw** [comment]
Thanks!

**Comment by Ataraxia12** [comment]
> > Solution： 1.pip install viser 2. git clone https://github.com/heheyas/viser 3. pip install -e viser 4. cd ..
> 
> That doesn't work for me. Doker image: 11.8.0-cudnn8-devel-ubuntu22.04. torch=2.0.1+cu118 pip 22.0.2

May be you can solve it by upgrating your pip version.

**Comment by zjcs** [comment]
#21 Hope it is helpful to you. @RobotiX101
