### ISSUE TITLE
An elegant way to install origin viser instead of modified viser

### ISSUE THREAD

**Issue by zjcs** [buaacyw/GaussianEditor#21]
I notice that author modify the origin viser to capture the scene click pixel (actually, it is normal pixel). Here is an implemention via the origin viser, which can be used in click_cb function:

            camera = list(self.server.get_clients().values())[0].camera
            W = int(self.resolution_slider.value)
            H = int(W / self.aspect)
            WH = torch.Tensor([W, H])
            fxy = WH/2 / np.tan(camera.fov/2)
            # TODO: fxy from different fovx, fovy?
            dxyz = tf.SO3(camera.wxyz).inverse().as_matrix() @ pointer.ray_direction
            uv = fxy * torch.Tensor(dxyz[:2])/dxyz[2] + WH/2
            click_pos = uv / WH

**Comment by zjcs** [comment]
By the way, it is a solution to #2

**Comment by buaacyw** [comment]
Thanks for your contribution!

**Comment by zjcs** [comment]
@buaacyw sorry to say that the above code has some bug when calucate fov via aspect, here is the right implemention:

        @self.server.on_scene_click
        def _(point):
               for client in self.server.get_clients().values():
                    camera = client.camera
                    ray_d = torch.Tensor(tf.SO3(camera.wxyz).inverse().as_matrix() @ point.ray_direction)
                    # ray_d, the ray in the camera, under the OpenGL coordination: x->right, y->up, z->far
                    xy_norm = ray_d[:2]/ray_d[2]
                    
                   WH = torch.Tensor([self.resolution_slider.value, self.resolution_slider.value/camera.aspect]).int()
                   tan_fov_2 = torch.Tensor([np.tan(camera.fov/2)*camera.aspect, np.tan(camera.fov/2)])
                   fxy = WH/2 / tan_fov_2

                    uv = (torch.Tensor(K[:2]) * xy_norm  + torch.Tensor(K[2:])).int()

                    click_pos = uv / WH

**Comment by jimmychuang95** [comment]
@zjcs I modify the webui.py code as you provided, but the bounded box and SAM points still cannot be added into scene, what else should I need to change to let those functions work?

**Comment by RAF3DA** [comment]
@zjcs I am getting FileNotFoundError even after replacing the click_cb function as mentioned, what are the exact changes?

**Comment by zjcs** [comment]
> @zjcs I am getting FileNotFoundError even after replacing the click_cb function as mentioned, what are the exact changes?

uninstall viser first and re install viser again. pip from wheel will install the prebuilt client. Otherwise you should build and install these client following viser doc

**Comment by RAF3DA** [comment]
> > @zjcs I am getting FileNotFoundError even after replacing the click_cb function as mentioned, what are the exact changes?
> 
> uninstall viser first and re install viser again. pip from wheel will install the prebuilt client. Otherwise you should build and install these client following viser doc

complete error-- after uninstalling and reinstalling viser via pip install -e viser, do we have to replace the entire click_cb function? Or just add your suggested changes?
(viser) No client build found. Building now...
 * Environment already exists: C:\Users\ZDF1KOR\Desktop\Projects\GaussianEditor\extern\viser\src\viser\client\.nodeenv
Traceback (most recent call last):
  File "webui.py", line 1579, in <module>
    webui = WebUI(args)
  File "webui.py", line 158, in __init__
    self.server = viser.ViserServer(port=self.port)
  File "C:\Users\ZDF1KOR\Desktop\Projects\GaussianEditor\extern\viser\src\viser\_viser.py", line 326, in __init__
    _client_autobuild.ensure_client_is_built()
  File "C:\Users\ZDF1KOR\Desktop\Projects\GaussianEditor\extern\viser\src\viser\_client_autobuild.py", line 57, in ensure_client_is_built
    env_dir = _install_sandboxed_node()
  File "C:\Users\ZDF1KOR\Desktop\Projects\GaussianEditor\extern\viser\src\viser\_client_autobuild.py", line 81, in _install_sandboxed_node
    subprocess.run(
  File "C:\Users\ZDF1KOR\.conda\envs\GaussianEditor\lib\subprocess.py", line 493, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\ZDF1KOR\.conda\envs\GaussianEditor\lib\subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\ZDF1KOR\.conda\envs\GaussianEditor\lib\subprocess.py", line 1327, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by zjcs** [comment]
Use viser wheel. If you pip from viser source code, you should build the client by youself

---- Replied Message ----
| From | Zohair ***@***.***> |
| Date | 10/23/2024 15:30 |
| To | buaacyw/GaussianEditor ***@***.***> |
| Cc | zjcs ***@***.***>,
Mention ***@***.***> |
| Subject | Re: [buaacyw/GaussianEditor] An elegant way to install origin viser instead of modified viser (Issue #21) |

@zjcs I am getting FileNotFoundError even after replacing the click_cb function as mentioned, what are the exact changes?

uninstall viser first and re install viser again. pip from wheel will install the prebuilt client. Otherwise you should build and install these client following viser doc

complete error-- after uninstalling and reinstalling viser via pip install -e viser, do we have to replace the entire click_cb function? Or just add your suggested changes?
(viser) No client build found. Building now...

Environment already exists: C:\Users\ZDF1KOR\Desktop\Projects\GaussianEditor\extern\viser\src\viser\client.nodeenv
Traceback (most recent call last):
File "webui.py", line 1579, in
webui = WebUI(args)
File "webui.py", line 158, in init
self.server = viser.ViserServer(port=self.port)
File "C:\Users\ZDF1KOR\Desktop\Projects\GaussianEditor\extern\viser\src\viser_viser.py", line 326, in init
_client_autobuild.ensure_client_is_built()
File "C:\Users\ZDF1KOR\Desktop\Projects\GaussianEditor\extern\viser\src\viser_client_autobuild.py", line 57, in ensure_client_is_built
env_dir = _install_sandboxed_node()
File "C:\Users\ZDF1KOR\Desktop\Projects\GaussianEditor\extern\viser\src\viser_client_autobuild.py", line 81, in _install_sandboxed_node
subprocess.run(
File "C:\Users\ZDF1KOR.conda\envs\GaussianEditor\lib\subprocess.py", line 493, in run
with Popen(*popenargs, **kwargs) as process:
File "C:\Users\ZDF1KOR.conda\envs\GaussianEditor\lib\subprocess.py", line 858, in init
self._execute_child(args, executable, preexec_fn, close_fds,
File "C:\Users\ZDF1KOR.conda\envs\GaussianEditor\lib\subprocess.py", line 1327, in _execute_child
hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by RAF3DA** [comment]
@zjcs 
Thank you, worked but with AttributeError: 'ViserServer' object has no attribute 'on_scene_click', might have to do with viser==0.2!

**Comment by zjcs** [comment]
Api is changed. Find the latest

---- Replied Message ----
| From | Zohair ***@***.***> |
| Date | 10/23/2024 18:52 |
| To | buaacyw/GaussianEditor ***@***.***> |
| Cc | zjcs ***@***.***>,
Mention ***@***.***> |
| Subject | Re: [buaacyw/GaussianEditor] An elegant way to install origin viser instead of modified viser (Issue #21) |

@zjcs
Thank you, worked but with AttributeError: 'ViserServer' object has no attribute 'on_scene_click', might have to do with viser==0.2!
