### ISSUE TITLE
AssertionError: please install our forked viser

### ISSUE THREAD

**Issue by Nieschlafen** [buaacyw/GaussianEditor#22]
When I try to add it, this issue pops up
  File "webui.py", line 587, in _
    self.click_cb(pointer)
  File "webui.py", line 841, in click_cb
    assert hasattr(pointer, "click_pos"), "please install our forked viser"
AssertionError: please install our forked viser

**Comment by buaacyw** [comment]
Hi! How did you install your environment? It looks like you didn't install our revised viser repo.

**Comment by Nieschlafen** [comment]
> Hi! How did you install your environment? It looks like you didn't install our revised viser repo.

I'm following the action under this link
https://github.com/nerfstudio-project/viser/tree/main

# Clone the repository.
git clone https://github.com/nerfstudio-project/viser.git

# Install the package.
# You can also install via pip: `pip install viser`.
cd ./viser
pip install -e .

and My viser version is 0.1.16
Is there a problem with the way I installed it, or am I installing the wrong version or something else？
Thank you very much for your reply！

**Comment by Nieschlafen** [comment]
I found my problem should be under this link,  git clone https://github.com/heheyas/viser 
I used the following viser link version before
