### ISSUE TITLE
A problem occurs during the webUI operation

### ISSUE THREAD

**Issue by VG-socool** [buaacyw/GaussianEditor#26]
Hello, Dr. Chen.I have a problem.I tried to run the webui, and encountered this problem: It's said that "No module named 'simple_knn'", but when I tried to install it with pip, it's said that "Requirement already satisfied".Thank you for your help!
![27440894f3ecbd45cb99cc3e2845dd3](https://github.com/buaacyw/GaussianEditor/assets/140047928/3bd5afa8-4561-4665-b733-334c2d55a81c)

**Comment by ScienceLi1125** [comment]
You may check `requirement.txt` which contains `gaussiansplatting/submodules/simple-knn`. Because `simple-knn` is installed by `pip install gaussiansplatting/submodules/simple-knn` instead of `pip install simple-knn`.
