### ISSUE TITLE
How can I output a rendered video of the edited scene?

### ISSUE THREAD

**Issue by ScienceLi1125** [buaacyw/GaussianEditor#27]
Hi, if I want to output a rendered video of the edited scene, how can I make it?

**Comment by buaacyw** [comment]
Hi, you need to specify a camera trajectory for rendering. You can interpolate between the known colmap cameras.

**Comment by Vincento-Wang** [comment]
> Hi, you need to specify a camera trajectory for rendering. You can interpolate between the known colmap cameras.

I render the video, but it looks edited video not continous, any problem ?

https://github.com/user-attachments/assets/5ca4fc06-c6bc-479a-96d2-74cad699abdc


https://github.com/user-attachments/assets/24fabcda-1df9-4df4-ba28-ab42f22d9bd3

**Comment by jingwu2121** [comment]
Hi, is it possible for you to share the render trajectory?

**Comment by Vincento-Wang** [comment]
> Hi, is it possible for you to share the render trajectory?

random select two view of frames, then use quaternion interpotation to render list of views.
