### ISSUE TITLE
No such file or directory: '.cache/dpt/omnidata_dpt_depth_v2.ckpt'

### ISSUE THREAD

**Issue by ScienceLi1125** [buaacyw/GaussianEditor#28]
When I use command line to add a teddy bear on bench in bicycle dataset by `python launch.py --config configs/add.yaml --train --gpu 0 data.source=../autodl-tmp/dataset/bicycle system.gs_source=../autodl-tmp/dataset/bicycle/point_cloud/iteration_7000/point_cloud.ply system.inpaint_prompt="a teddy bear on bench" system.refine_prompt="make it a teddy bear" system.cache_overwrite=False system.cache_dir="add_bear"  trainer.max_steps=1  system.loggers.wandb.enable=true system.loggers.wandb.name="add_bear"`, I have encountered this problem: `FileNotFoundError: [Errno 2] No such file or directory: '.cache/dpt/omnidata_dpt_depth_v2.ckpt'` and the program was interrupted.

By the way, the terminal also outputs `Traceback (most recent call last):
  File "launch.py", line 7, in <module>
    if os.environ['USER']=="yiwen":
  File "/root/miniconda3/lib/python3.8/os.py", line 675, in __getitem__
    raise KeyError(key) from None
KeyError: 'USER'`, does it matters?

**Comment by buaacyw** [comment]
Hi! Could you please tell me your device environment?
For the missed ckpt, it should be automatically downloaded. 
You can remove `os.environ['USER']=="yiwen" `.

**Comment by ScienceLi1125** [comment]
> Hi! Could you please tell me your device environment? For the missed ckpt, it should be automatically downloaded. You can remove `os.environ['USER']=="yiwen" `.

Thank you for your reply. I solved the problem by downloading [omnidata_dpt_depth_v2.ckpt](https://huggingface.co/camenduru/PeRF/blob/main/omnidata_dpt_depth_v2.ckpt) and uploading it to `.cache/dpt`.

If possible, can you tell me at which step ckpt is automatically downloaded?

**Comment by Nieschlafen** [comment]
Do you still encounter this problem during the add operation?
 File "webui.py", line 532, in _
    self.add(self.camera)
  File "/home/miniconda3/envs/GaussianEditor/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "webui.py", line 1566, in add
    new_object_gaussian.load_ply(gs_path)
  File "/home/desktop/GaussianEditor/gaussiansplatting/scene/vanilla_gaussian_model.py", line 293, in load_ply
    plydata = PlyData.read(path)
  File "/home/miniconda3/envs/GaussianEditor/lib/python3.8/site-packages/plyfile.py", line 158, in read
    (must_close, stream) = _open_stream(stream, 'read')
  File "/home/miniconda3/envs/GaussianEditor/lib/python3.8/site-packages/plyfile.py", line 1345, in _open_stream
    return (True, open(stream, read_or_write[0] + 'b'))
FileNotFoundError: [Errno 2] No such file or directory: '/home/yjx/desktop/GaussianEditor/tmp_add/inpaint_gs.obj'

How are these two obj files created in line 1322 of the code?
        mesh_path = os.path.join(cache_dir, "inpaint_mesh.obj")
        gs_path = os.path.join(cache_dir, "inpaint_gs.obj")

**Comment by jingyangcarl** [comment]
I have the same problem using "Add"

**Comment by Nieschlafen** [comment]
> I have the same problem using "Add"

I have the same issue, but I solved it from this answer, but this is still a new problem，
https://github.com/buaacyw/GaussianEditor/issues/10
I kept trying to conda update ffmpeg but it didn't work, and my tmp_add didn't inpaint_gs.obj this file, do you know where this file is generated in the code? It's still there as it is.
You can try it according to my link above, and if it is solved, I hope we can continue to talk about it.

**Comment by jingyangcarl** [comment]
> > I have the same problem using "Add"
> 
> I have the same issue, but I solved it from this answer, but this is still a new problem， #10 I kept trying to conda update ffmpeg but it didn't work, and my tmp_add didn't inpaint_gs.obj this file, do you know where this file is generated in the code? It's still there as it is. You can try it according to my link above, and if it is solved, I hope we can continue to talk about it.

It works. Thanks
