### ISSUE TITLE
Adding operation related question

### ISSUE THREAD

**Issue by john123zerg** [buaacyw/GaussianEditor#29]
Hello!
<img width="669" alt="image" src="https://github.com/buaacyw/GaussianEditor/assets/63462803/d9293ef0-ceda-4410-8838-3875cac8e281">
<img width="683" alt="image" src="https://github.com/buaacyw/GaussianEditor/assets/63462803/011e03cd-515c-45f1-9770-354ad1370256">

I tried adding a car in my view, and it worked fine. The problem is that it only had that view of the car. So, if I rotated the view an inch, the car disappears.

However, in your demo with the teddy bear, it seemed it was a 3d object.

How did you do that?

**Comment by jingyangcarl** [comment]
Hi, I have the same problem here. Any chance you can let me know how you resolve it? thanks.

**Comment by john123zerg** [comment]
Can you provide details of your problem?
I handled my one. I figured out 'End 2D Inpainting' would lead to Wonder3D.
At that time, I didn't install Wonder3D precisely.



> Hi, I have the same problem here. Any chance you can let me know how you resolve it? thanks.

**Comment by jingyangcarl** [comment]
> Can you provide details of your problem? I handled my one. I figured out 'End 2D Inpainting' would lead to Wonder3D. At that time, I didn't install Wonder3D precisely.
> 
> > Hi, I have the same problem here. Any chance you can let me know how you resolve it? thanks.

Thanks for the reply. Indeed it's caused by Wonder3D. I solved it with the installation. Thanks.
