### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 

### ISSUE THREAD

**Issue by cwwjyh** [buaacyw/GaussianEditor#32]
I have successfully installed viser by following the instructions below:
mkdir extern && cd extern
git clone https://github.com/heheyas/viser 
pip install -e viser
cd ..
but when I run "python webui.py --gs_source <your-ply-file> --colmap_dir <dataset-dir>" it occur some questions as follow:
![31754684f4ef9b1b2e8973d9e30e0b8](https://github.com/buaacyw/GaussianEditor/assets/26154160/760bd8aa-f109-4114-8317-370cefac525b)

![cdcfab2193f040c3b99de2d49a5d221](https://github.com/buaacyw/GaussianEditor/assets/26154160/ea3850d4-ebc5-4e5e-b823-478d8d73c25b)
i also attempt [](https://github.com/buaacyw/GaussianEditor/issues/2) upgrade pip. but it also didn't work.  Can you give me some advice? Thank you!
my environment is:
torch==2.0.1+cu117 
torchvision==0.15.2+cu117
pip=24.0

**Comment by zjcs** [comment]
Hope this issue is helpful to you: #21

**Comment by cwwjyh** [comment]
@zjcs Thank you! When I change a server, it can easily install **viser** and run successfully.

**Comment by jimmychuang95** [comment]
@cwwjyh I encountered same problem when running code below and I modify the webui.py code with #21 , but  problem did not solve. May I ask how do you solve this problem?

python webui.py \
    --colmap_dir ./dataset/bicycle\
    --gs_source ./dataset/bicycle/point_cloud/iteration_7000/point_cloud.ply

**Comment by RAF3DA** [comment]
@cwwjyh I am having the same error what are the changes that you exactly made?
