### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '~/projects/GaussianEditor/tmp_add/multiview_pred_images/rgb_000_front.png' 

### ISSUE THREAD

**Issue by jingyangcarl** [buaacyw/GaussianEditor#34]
I'm encountering this issue when using "Add" mode following the instruct. Any idea of fixing this?

**Comment by sora158** [comment]
Same issue here

**Comment by sucy171106** [comment]
Same issue here

**Comment by Deaddawn** [comment]
> I'm encountering this issue when using "Add" mode following the instruct. Any idea of fixing this?

Hi, how do you fix this?

**Comment by Maddog241** [comment]
Maybe there's something wrong with wonder3d
For me, I found the wonder3d ckpts are broken so I redownloaded them and changed `pretrained_unet_path` in `threestudio/utils/wonder3D/configs/mvdiffusion-joint-ortho-6views.yaml` to absolute path. And it worked.
