### ISSUE TITLE
Can i run it with a 16G GPU(RTX 2080 ti)?

### ISSUE THREAD

**Issue by CoderColder2001** [buaacyw/GaussianEditor#36]
Sorry for my poor knowledge about Machine Learning and 3dGS... When running this project (with test data "bicycle.ply")i always encounter CUDA OUTOFMEMORY ERROR. How should I do or set if it is possible to run with a 16G GPU ? (my cuda version is 11.8)

**Comment by buaacyw** [comment]
That depends on the size of the gaussian scenes and "bicycle.ply" is a quite large one. Please try smaller scenes such as face editing.
