### ISSUE TITLE
Question about paper GaussianEditor

### ISSUE THREAD

**Issue by CrescentRosexx** [buaacyw/GaussianEditor#40]
Thanks for your excellent work!!
The idea of HGS is very genius. As for the previous work GSGEN, DreamGaussian and GaussianDreamer mentioned in the paper, "GS has shown limitations when facing the randomness of generative guidance."
I would like to know what this challenge is specifically, because I don't remember any mention of this in these papers. Does it mean that their results are not so good, so speculate on the reason?

**Comment by buaacyw** [comment]
Thanks for your interests! The result of those papers is nice in the context of text-to-3D or image-to-3D. But for 3D editing, we expect the result to be realistic as real world. 
In my understanding, the main limitations mentioned in these papers is that GS tends to become foggy under generative guidance.
