### ISSUE TITLE
Issue about setting up the environment when install diff_gaussian_rasterization and simple_knn

### ISSUE THREAD

**Issue by Deaddawn** [buaacyw/GaussianEditor#41]
Hi, i met an input/output problem when setting the environment using conda, terminal info: 

      creating build/bdist.linux-x86_64/wheel/simple_knn
      copying build/lib.linux-x86_64-cpython-38/simple_knn/_C.cpython-38-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/wheel/simple_knn
      running install_egg_info
      running egg_info
      writing simple_knn.egg-info/PKG-INFO
      writing dependency_links to simple_knn.egg-info/dependency_links.txt
      writing top-level names to simple_knn.egg-info/top_level.txt
      reading manifest file 'simple_knn.egg-info/SOURCES.txt'
      writing manifest file 'simple_knn.egg-info/SOURCES.txt'
      Copying simple_knn.egg-info to build/bdist.linux-x86_64/wheel/simple_knn-0.0.0-py3.8.egg-info
      **error: [Errno 5] Input/output error: 'build/bdist.linux-x86_64/wheel/simple_knn-0.0.0-py3.8.egg-info/SOURCES.txt'**
      [end of output]
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for simple_knn
  Running setup.py clean for simple_knn
Failed to build diff_gaussian_rasterization simple_knn
ERROR: Could not build wheels for diff_gaussian_rasterization, simple_knn, which is required to install pyproject.toml-based projects

**Comment by Deaddawn** [comment]
Solved.

**Comment by LitCaesala** [comment]
wow, great job, i also encounter the same question, i tried the others method, but didn't work for me, how did you resolve it?

**Comment by fawnliu** [comment]
Note to finish the command in `install.sh`.
```
cd gaussiansplatting/submodules
pip install ./diff-gaussian-rasterization
pip install ./simple-knn
```
