### ISSUE TITLE
No such file or directory: '/root/szd/GaussianEditor/add_cache/add_dog/inpaint_a_dog_on_the_bench/multiview_pred_images/rgb_000_front.png'

### ISSUE THREAD

**Issue by Deaddawn** [buaacyw/GaussianEditor#45]
Hi, using add_dog.sh, get this error:

No such file or directory: '/root/szd/GaussianEditor/add_cache/add_dog/inpaint_a_dog_on_the_bench/multiview_pred_images/rgb_000_front.png'

any idea how to fix this?

**Comment by yyyhz** [comment]
Could you please tell me how to solve this problem?

**Comment by Devin100086** [comment]
@Deaddawn I also have the same problem. Could you please tell me how to solve this problem?
