### ISSUE TITLE
expected scalar type Float but found BFloat16

### ISSUE THREAD

**Issue by Devin100086** [buaacyw/GaussianEditor#75]
Dear authors, thank you for your impressive work.

When I run the **launch.py**, I encountered an issue during training. "**expected scalar type Float but found BFloat16**",How can I resolve it?

Thank you

**Comment by yyhyyhyyhyyh** [comment]
I've encountered the same problem, do you have a solution?

**Comment by ZiyangYan** [comment]
I have the same problem too

**Comment by ZiyangYan** [comment]
@yyhyyhyyhyyh solution here https://github.com/silent-chen/DGE/issues/11#issuecomment-2456971913

**Comment by yyhyyhyyhyyh** [comment]
Thank you!
