### ISSUE TITLE
code about IN2N data to gs-data type

### ISSUE THREAD

**Issue by Alex-Zhu1** [buaacyw/GaussianEditor#76]
Hi,

I am looking for code that can process IN2N data into gs-data format. I found that the IN2N OpenCV data only includes a transforms.json file, and the COLMAP data seems to be useless for COLMAP reconstruction for gs-data.

Any help would be appreciated!

Thank you!

**Comment by WarrenZZZZL** [comment]
> Hi,
> 
> I am looking for code that can process IN2N data into gs-data format. I found that the IN2N OpenCV data only includes a transforms.json file, and the COLMAP data seems to be useless for COLMAP reconstruction for gs-data.
> 
> Any help would be appreciated!
> 
> Thank you!

Hi, how do you solve this problem

**Comment by Alex-Zhu1** [comment]
> Hi,
> 
> I am looking for code that can process IN2N data into gs-data format. I found that the IN2N OpenCV data only includes a transforms.json file, and the COLMAP data seems to be useless for COLMAP reconstruction for gs-data.
> 
> Any help would be appreciated!
> 
> Thank you!



> > 你好，
> > 我正在寻找可以将 IN2N 数据处理为 gs-data 格式的代码。我发现 IN2N OpenCV 数据仅包含一个 transforms.json 文件，而 COLMAP 数据似乎对于 gs-data 的 COLMAP 重建毫无用处。
> > 任何帮助都将不胜感激！
> > 谢谢你！
> 
> 你好，你如何解决这个问题

Actually， u can  using gs offical code to process, but  it is suffer from some resolution issue. u maybe need to pre-processing resolution.
